[program:playback_server]
command= /usr/local/eventide/code/playback/target/release/playback
directory=/usr/local/eventide/code
autorestart=true
autostart=true
user = %(ENV_USER)s
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=2
