[supervisord]
#nodaemon=true

[inet_http_server]         ; inet (TCP) server disabled by default
port=*:8080        ; (ip_address:port specifier, *:port for all iface)
;username=daedalus              ; (default is no username (open server))
;password=daedalus               ; (default is no password (open server))

[program:event_based_camera]
command= /usr/local/eventide/code/evk_datalogger --output-dir SEDPLACEHOLDER/evk/
directory=/usr/local/eventide/code
autorestart=true
autostart=false
user = %(USER)s
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=1

[program:evk_mjpeg_server]
command= /usr/local/eventide/code/viewfinder --bind 0.0.0.0:8081
directory=/usr/local/eventide/code
autorestart=true
autostart=false
user = %(USER)s
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=2

[program:pi_camera_datalogger]
command= /usr/bin/python /usr/local/eventide/code/camera_app.py --output-dir SEDPLACEHOLDER/picam/ --config /usr/local/eventide/config/camera_config.json
directory=/usr/local/eventide/code
autorestart=true
autostart=false
user = %(USER)s
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=1

[program:pi_mjpeg_server]
command= /usr/bin/python /usr/local/eventide/code/mjpeg_server.py --port 8082
directory=/usr/local/eventide/code
autorestart=true
autostart=false
user = %(USER)s
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=2

[program:infrared_camera]
command= /usr/local/eventide/code/ircam SEDPLACEHOLDER/ircam/
directory=/usr/local/eventide/code
autorestart=true
autostart=false
user = %(USER)s
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=1

# [program:eventide_dashboard]
# command= /usr/bin/python /home/tripwire/eventide/code/dashboard.py --html-file code/dashboard.html --recordings-dir /home/tripwire/eventide/recordings/
# directory=/home/tripwire/eventide
# autorestart=true
# autostart=false
# user = tripwire
# #startsecs=0
# startretries=10000
# stdout_logfile=/var/log/supervisor/%(program_name)s.log
# priority=2
