[supervisord]
#nodaemon=true

[inet_http_server]         ; inet (TCP) server disabled by default
port=*:8080        ; (ip_address:port specifier, *:port for all iface)
;username=daedalus              ; (default is no username (open server))
;password=daedalus               ; (default is no password (open server))

[program:event_based_camera]
command= /home/tripwire/evk_datalogger/target/release/evk_datalogger --output-dir evk_datalogger/recordings/
directory=/home/tripwire/evk_datalogger
autorestart=true
autostart=false
user = tripwire
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=1

[program:evk_mjpeg_server]
command= /home/tripwire/evk_datalogger/target/release/viewfinder --bind 0.0.0.0:8081
directory=/home/tripwire/evk_datalogger
autorestart=true
autostart=false
user = tripwire
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=2

[program:pi_camera_datalogger]
command= /usr/bin/python /home/tripwire/picam_datalogger/camera_app.py --output-dir /home/tripwire/picam_datalogger/recordings/ --config /home/tripwire/picam_datalogger/camera_config.json
directory=/home/tripwire/picam_datalogger
autorestart=true
autostart=false
user = tripwire
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=1

[program:pi_mjpeg_server]
command= /usr/bin/python /home/tripwire/picam_datalogger/mjpeg_client.py --port 8082
directory=/home/tripwire/picam_datalogger
autorestart=true
autostart=false
user = tripwire
#startsecs=0
startretries=10000
stdout_logfile=/var/log/supervisor/%(program_name)s.log
priority=2